#!/bin/bash -f
#
if [ -f /etc/bash.bashrc ]; then
    . /etc/bash.bashrc
fi

for guy in "Dog_1" "Dog_2" "Dog_3" "Dog_4"  "Dog_5" "Patient_1" "Patient_2"
do
cat > scriptx$guy << EOF
#!/bin/bash -f
#SBATCH --qos=normal
#SBATCH -n1 --time=23:59:00 --mem-per-cpu=1gb
#SBATCH -J hackathon

cd /nfs/nhome/live/vincenta/git/gatsby-hackathon-seizure/code/python/seizures/submission/
python submission_forest_predictor.py "$guy" "$guy"
EOF
chmod a+x scriptx$guy
sbatch scriptx$guy

done




